version: "3.8"
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/srv/www/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - nodejs
      - mysql
      - pg
  nodejs:
    image: node:alpine
    environment:
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./node-app:/home/app
    depends_on:
      - php
    command: ["npm", "run", "start:dev"]
  php:
    image: webdevops/php-apache-dev:8.2
    ports:
      - 8081:80
    volumes:
      - ./php-app:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    depends_on:
      - pg
    restart: always
    ports:
      - 8080:8080
volumes:
  pg-data:
  mysql-data:
